spring:
  security:
    oauth2:
      client:
        registration:
          #Google
          google:
            client-id: 101274233050-528rk0ej6i9d1qkjgmjt4sm0dd5rfu3v.apps.googleusercontent.com
            client-secret: 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
            redirectUri: http://j8b304.p.ssafy.io:8080/login/oauth2/code/google
            scope: profile,email
          #kakao
          kakao:
            client-id: 2787aaa3471a6b9509332d74986caec0
            client-secret: bfCgKX23CY2ktzAGuq3C4u1IgQsHO8Gs
            scope: profile_nickname,account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://j8b304.p.ssafy.io:8080/login/oauth2/code/kakao
            logout-redirect-uri: http://j8b304.p.ssafy.io:8080/logout/kakao
            client-authentication-method: POST
          naver:
            client-id: EJLbtiYncykaCLVttDrg
            client-secret: 681fGtc1aq
            scope: nickname,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


