server:
  port: 8080


spring:
  application:
    name: user-service
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/eighteen?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
#    username: blur
#    password: blur
    url: jdbc:mysql://j8b304.p.ssafy.io:3306/eighteen?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
    username: root
    password: b304b304
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds8d9sfasd87w9d88as7d897ds78das7d7as8d78qw78d789as7ds87'
