stages:          # List of stages for jobs, and their order of execution
  - libs
  - build
  - deploy


npm:
  stage: libs
  only:
    - develop
  # only:
  #   - dev
  cache:
    paths:
      - react-project/node_modules
  script:
    - cd react-project
    - npm install


react-project:
  stage: build
  only:
    - develop
  cache:
    paths:
      - react-project/node_modules
  script:
    - cd react-project
    - CI=false npm run build
    

user-service:
  stage: build
  only:
    - develop
  script:
    - cd user-service
    - chmod +x gradlew
    - ./gradlew clean bootJar

deploy-job-react-project:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    - develop

    # if the script exit code is 137 or 255 the job will allow to be failed and the pipeline will continue to run
    # 'allow_failure'의 default는 boolean 값에 대해 대해서만 적용이 되어있음.
  allow_failure:
    exit_codes: # User defined exit code
    - 1

  script:
    - docker container stop react-project

    # - echo -e "\033[32mDeploying application...\033[0m"
    # - echo -e "\033[32m'react project' will be starting...\033[0m"
    # - docker container stop react-project
    # - docker container rm react-project
    # - docker build -t react-project .
    # - docker run -p 3000:3000 --name react-project react-project

# deploy-job-user-service:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   only:
#     - develop
#   allow_failure: true
#   script:
#     - echo -e "\033[32mDeploying application...\033[0m"
#     - echo -e "\033[32m'user service' will be starting...\033[0m"
#     - docker container stop user-service
#     - docker container rm user-service
#     - docker build -t user-service .
#     - docker run -p 3000:3000 --name user-service user-service
