stages:          # List of stages for jobs, and their order of execution
  - libs
  - build
  - deploy


npm:
  stage: libs
  only:
    - develop
  # only:
  #   - dev
  cache:
    paths:
      - react-project/node_modules
  script:
    - cd react-project
    - npm install
    - exit 1


react-project:
  stage: build
  only:
    - develop
  cache:
    paths:
      - react-project/build
      - react-project/node_modules
  needs: ["npm"]
  when: on_success
  script:
    - cd react-project
    - CI=false npm run build
    - docker build -t react-project .

react-project2:
  stage: build
  only:
    - develop
  cache:
    paths:
      - react-project/build
      - react-project/node_modules
  needs: ["npm"]
  when: on_failure
  script:
    - cd react-project

deploy-job/react-project:preparing_for_replace:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    - develop
  needs: ["react-project"]
  allow_failure: true
  when: on_success
  script:
    - docker container stop react-project && docker container rm react-project



deploy-job/react-project:replace_docker_container:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    - develop
  needs: ["deploy-job/react-project:preparing_for_replace"]
  # allow_failure: true
  when: on_success
  script:
    - docker run -p 3000:3000 --name react-project -d react-project






user-service:
  stage: build
  only:
    - develop
  script:
    - cd user-service
    - chmod +x gradlew
    - ./gradlew clean bootJar
    - docker build -t user-service .

deploy-job/user-service:preparing_for_replace:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    - develop
  needs: ["user-service"]
  allow_failure: true
  when: on_success
  script:
    - docker container stop user-service && docker container rm user-service

deploy-job/user-service:replace_docker_container:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    - develop
  needs: ["deploy-job/user-service:preparing_for_replace"]
  # allow_failure: true
  when: on_success
  script:
    - docker run -p 9001:8080 --name user-service -d user-service
