stages:          # List of stages for jobs, and their order of execution
  - libs
  # - build
  # - deploy


npm:
  stage: libs
  # only:
  #   - dev
  cache:
    paths:
      - react-project/node_modules
  script:
    - cd react-project
    - npm install
