stages:          # List of stages for jobs, and their order of execution
  - libs
  # - build
  # - deploy


npm:
  stage: libs
  # only:
  #   - dev
  cache:
    paths:
      - react-project/node_modules
  script:
    - cd react-project
    - npm install
    - npm run build
    # - tar -cvf dist.tar dist
  artifacts:
    name: "react-project-dist"
    expire_in: 30 days
    paths:
      - dist/*
