stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  only:
    - devops-component/api-gateway/develop
  script:
    - echo -e "\033[32mbuilding docker image(nginx-api gateway)\033[0m"
    - docker build -t api-gateway .


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    - devops-component/api-gateway/develop
  allow_failure: true
  script:
    - echo -e "\033[32mDeploying application...\033[0m"
    - docker container stop api-gateway
    - docker container rm api-gateway
    - sleep 1
    - docker run -p 80:80 --name api-gateway api-gateway
