stages:          # List of stages for jobs, and their order of execution
  - libs
  - build
  # - deploy


npm:
  stage: libs
  only:
    - develop
  # only:
  #   - dev
  cache:
    paths:
      - react-project/node_modules
  script:
    - cd react-project
    - npm install


react-project:
  stage: build
  only:
    - develop
  cache:
    paths:
      - react-project/node_modules
  script:
    - cd react-project
    - CI=false npm run build
    

user-service:
  stage: build
  only:
    - develop
  script:
    - cd user-service
    - chmod +x gradlew
    - ./gradlew clean bootJar

