spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8b304.p.ssafy.io:3306/eighteen?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
    username: root
    password: b304b304



  jpa:
    show-sq: true
    hibernate:
      ddl-auto: validate # update
    properties:
      hibernate:
        format_sql: true